///////////////////////////////////////////////////////////
//  DataBaseViewModel.cs
//  Implementation of the Class DataBaseViewModel
//  Generated by Enterprise Architect
//  Created on:      28-ιπε-2025 22:32:06
//  Original author: pilol
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using BankingCommunication;
namespace Server {
	public class DataBaseViewModel {



		~DataBaseViewModel() {

		}

		public DataBaseViewModel() {

		}

		/// 
		/// <param name="command"></param>
		public Data FetchDataByCommand(ICommand command) {

			return null;
		}

		public Data FetchLogInData() {

			return null;
		}

	}//end DataBaseViewModel

	public class Data
	{

	}
}//end namespace Server