///////////////////////////////////////////////////////////
//  ExceptionHandler.cs
//  Implementation of the Class ExceptionHandler
//  Generated by Enterprise Architect
//  Created on:      28-ιπε-2025 22:32:06
//  Original author: pilol
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Server {
	public static class ExceptionHandler {


		public static void ExceptionHandle(Exception exception){

		}

	}

}